### ISSUE TITLE
<a> tag is missing 'download' attribute

### ISSUE THREAD

**Issue by wakingrufus** [Kotlin/kotlinx.html#108]
The `<a>` tag should have a 'rel' attribute:
https://www.w3schools.com/TAGS/att_a_rel.asp

**Comment by Mystery406** [comment]
it seems 'download' attribute is missing too.

**Comment by wakingrufus** [comment]
I figured out how to do this (rel):
```
                       a(href = "url") {
                            rel = "rel"
                            +"link text"
                        }
```
download does seem to be missing though
