### ISSUE TITLE
TEXTAREA class should have a `value` property

### ISSUE THREAD

**Issue by rnikander** [Kotlin/kotlinx.html#119]
Should this class have a property `value: String` just like the `<input type='text'` elements do?

**Comment by reisi007** [comment]
Textarea has no value, the value is between the tags

**Comment by rnikander** [comment]
Ah, I see. I didn't realize the HTML spec here was different than the Javascript object attributes, which do have `value`. 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement

I'll close this.
