### ISSUE TITLE
Add support to <summary> tag

### ISSUE THREAD

**Issue by BraisGabin** [Kotlin/kotlinx.html#127]
Add support for the [`<summary>`](https://www.w3.org/TR/html52/interactive-elements.html#the-summary-element) tag

**Comment by dector** [comment]
@`contributors`, what's consensus about this? Are PRs welcomed?

**Comment by dmitrievanthony** [comment]
Hi @BraisGabin, @dector,

I added this tag, it will be available in the next release `0.7.2`.
