### ISSUE TITLE
missing tag figcaption

### ISSUE THREAD

**Issue by holgerbrandl** [Kotlin/kotlinx.html#13]
The figcaption tag is missing in the kotlinx DSL.

See http://w3c.github.io/html-reference/figcaption.html

In fact it would be even more helpful if the docs could detail out how to add a custom tag on top of the existing library (if this is possible with kotlinx) (ie to show how to extend the kotlinx DSL).  In https://github.com/kotlin/kotlinx.html/wiki/Micro-templating-and-DSL-customizing you already do so to some extent, but custom tags don't seem not to be covered there.

For now the only workaround seems to be 
```
StringBuilder().apply {
    appendHTML().figure() {
        img {
            src = movie.movieInfo?.coverImageURL
        }
    }
    append("<figcaption class='picture-item__title pull-left'>" + movie.name + """</figcaption>""")
}
```
but by using kotlinx I'd like to avoid simple unstructured string-building.

**Comment by cy6erGn0m** [comment]
@holgerbrandl sure, you shouldn't. Btw you can't append tags by `append` as the content will be escaped. You need to use `unsafe` for that purpose.

Let me look at the tag definition

**Comment by cy6erGn0m** [comment]
https://github.com/Kotlin/kotlinx.html/wiki/Micro-templating-and-DSL-customizing#introduce-custom-tag

**Comment by cy6erGn0m** [comment]
https://github.com/Kotlin/kotlinx.html/wiki/Development#if-something-is-missing

**Comment by cy6erGn0m** [comment]
Fixed in 0.5.7

**Comment by holgerbrandl** [comment]
Thanks for the fast doc-update. Worked great for me to add `figcaption`.  Imbho capitalization is wrong in the extension function of the example : Instead of `fun DIV.CUSTOM(...)` it should be `fun DIV.custom(...)`

**Comment by cy6erGn0m** [comment]
@holgerbrandl ops, just an accident
