### ISSUE TITLE
Attribute names don't accept Alpine.js directives

### ISSUE THREAD

**Issue by wyaeld** [Kotlin/kotlinx.html#135]
`alpine.js` has directives expressed in html attribute like 

```html
<div x-data="{ sidebarOpen: false }" @keydown.window.escape="sidebarOpen = false">
```

The problem is the `@` prefix on the 2nd attribute.  This appears to be the same as https://github.com/Kotlin/kotlinx.html/issues/118 which is also unresolved.

Both issues appear valid according to the html spec referenced in https://github.com/Kotlin/kotlinx.html/issues/118, but kotlinx.html is silently discarding them

**Comment by wyaeld** [comment]
@cy6erGn0m would it be hard to fix both of these?

**Comment by wyaeld** [comment]
This can be worked around a longer form, which looks like

```kotlin
attributes["x-on:keydown.window.escape"] = "sidebarOpen = false"
```

instead of 

```kotlin
attributes["@keydown.window.escape"] = "sidebarOpen = false"
```

but the later is still valid to the html spec, so whether is should be supported is the question

**Comment by lgwillmore** [comment]
Any news on this?

There are many frameworks which have this syntax

**Comment by cies** [comment]
For sake of completing this issue: Alpine.js' `:class` attribute also does (did) not go well with kotlinx.html. It results in a `Tag div has invalid attribute name :class` error. The work around in that case was using `x-bind:class` instead.
