### ISSUE TITLE
How to use this in Android project?

### ISSUE THREAD

**Issue by ionull** [Kotlin/kotlinx.html#145]
I imported jvm library through gradle, while can't use DSLs in my project.

**Comment by mddanishansari** [comment]
I also have the same issue

**Comment by mddanishansari** [comment]
This is how you can use it int Android or any Kotlin/JVM project

```kotlin
fun getHtml(): String {
    val html = StringBuilder().appendHTML().html {
        body {
            h1("Hello world!")
        }
    }.toString()

    return html
}
```

**Comment by carterhudson** [comment]
The documentation is very poor. Thanks for this.

**Comment by FilippoVigani** [comment]
This doesn't work for me. I can't seem to find the dependency.
