### ISSUE TITLE
Support `blockquote`

### ISSUE THREAD

**Issue by digitalheir** [Kotlin/kotlinx.html#150]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

**Comment by tobiasletcher-ap** [comment]
@digitalheir I believe the blockQuote tag [is supported]( https://github.com/Kotlin/kotlinx.html/blob/c3afca79ac761f074ce7e24f784c0a64d041858d/src/commonMain/kotlin/generated/gen-tag-groups.kt#L40 )

**Comment by digitalheir** [comment]
Weird how I missed that, thanks!
