### ISSUE TITLE
Jcenter stopped providing the dependency

### ISSUE THREAD

**Issue by hamen** [Kotlin/kotlinx.html#151]
Hi all,

We started getting 
```
 > Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.1.
```
a couple of hours ago and we had to update our configuration, adding a new maven repo:

```
maven { url "https://dl.bintray.com/kotlin/kotlinx" }
```

I would like to update the "Getting started" documentation, but I'm a bit afraid about modifying the wiki page 😂
However I hope this issue can help others ☮️

**Comment by wilj** [comment]
Same error for version 0.6.12:

> Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.6.12.

Adding the new maven repo does not fix the issue, since the new repo only has 0.7.1

**Comment by hamen** [comment]
@wilj can you try this other repo please?

```
maven { url  "https://kotlin.bintray.com/kotlinx" }
```

**Comment by wilj** [comment]
> @wilj can you try this other repo please?
> 
> ```
> maven { url  "https://kotlin.bintray.com/kotlinx" }
> ```

That worked, thanks!

**Comment by lsoares** [comment]
thanks! also worked for me - using version `0.7.1,` the only available.

**Comment by jbaruch** [comment]
The artifact was unlinked from JCenter per Kotlin's team request.

**Comment by 1jGabriel** [comment]
This works for me too, thanks evertone 
maven { url "https://dl.bintray.com/kotlin/kotlinx" }

**Comment by amelluk** [comment]
> The artifact was unlinked from JCenter per Kotlin's team request.

Any idea why? this has caused lots of pain here and late delivery...

**Comment by cortinico** [comment]
> The artifact was unlinked from JCenter per Kotlin's team request.

@jbaruch The Bintray UI is a bit confusing as the package page says that it's still linked in JCenter:
https://bintray.com/kotlin/kotlinx/kotlinx.html Though the artifacts are missing:

![Screenshot 2020-07-17 at 20 01 40](https://user-images.githubusercontent.com/3001957/87817046-87e04f80-c868-11ea-8317-4eedeafb5d5c.png)

Is that a result of caching?

**Comment by jbaruch** [comment]
They've added a `kotlin` prefix. It's under `kotlin/kotlinx/kotlinx.html` now: 

1.https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-html/

2.https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-html-assembly/

3.https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-html-common/

4.https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-html-js/

5.https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-html-jvm/

**Comment by jschlicht** [comment]
We're stuck on kotlinx-html 0.6.x due to this compilation performance bug: https://github.com/Kotlin/kotlinx.html/issues/147

Here's the repo we had to add to get 0.6.12 to download again and fix our build:
`maven { url = uri("https://dl.bintray.com/kotlin/kotlinx.html") }`

**Comment by cortinico** [comment]
> The artifact was unlinked from JCenter per Kotlin's team request.

@jbaruch It seems like that the URL that was failing to resolve (https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.1/kotlinx-html-jvm-0.7.1.pom) it's now working again (at least for us on Detekt https://github.com/detekt/detekt/issues/2882).

Is the issue solved?

**Comment by jbaruch** [comment]
Yes, we linked the old coordinates back. So now both old and new should work.

**Comment by bashor** [comment]
Hi, everybody!

We are sorry for the inconvenience!

Right now you can continue using 0.7.1 from JCenter. 
If you use an older version we recommend you update to 0.7.1 and continue using it from JCenter.
If you want to stay on an older version you can use this maven repository https://dl.bintray.com/kotlin/kotlinx.html to get it, 
but **note** new versions will come only to the new repo (https://kotlin.bintray.com/kotlinx) and JCenter.

Code snippet to define repo in Gradle:
```groovy
maven {
    url("https://dl.bintray.com/kotlin/kotlinx.html")
}
```

**Comment by bashor** [comment]
Happy to share that we've restored 0.6.* artifacts in JCenter.

Have a nice Kotlin!

**Comment by xxroot** [comment]
> ```groovy
>  https://dl.bintray.com/kotlin/kotlinx.html
> ```

It's dead. I can't build it now magisk20.4

**Comment by xxroot** [comment]
> 大家好！
> 
> 对此造成的不便，我们表示歉意！
> 
> 现在您可以继续使用 JCenter 的 0.7.1。 如果您使用旧版本，我们建议您更新到 0.7.1 并继续从 JCenter 使用它。 如果您想继续使用旧版本，您可以使用这个 maven 存储库https://dl.bintray.com/kotlin/kotlinx.html来获取它， 但**请注意**新版本只会出现在新存储库中（[https:// kotlin.bintray.com/kotlinx](https://kotlin.bintray.com/kotlinx)）和 JCenter。
> 
> 在 Gradle 中定义 repo 的代码片段：
> 
> ```groovy
> 存储库{
>     行家{
>         网址  “ https://dl.bintray.com/kotlin/kotlinx.html ” 
>     }
> }
> ```

It's dead. I can't build it now magisk20.4

**Comment by Tapchicoma** [comment]
@xxroot check [this documentation](https://github.com/kotlin/kotlinx.html/wiki/Getting-started)
