### ISSUE TITLE
Bootstrap Properties

### ISSUE THREAD

**Issue by sangeetds** [Kotlin/kotlinx.html#160]
Hi. 
I was just wondering whether the code given in [MicroTemplating section of the wiki](https://github.com/Kotlin/kotlinx.html/wiki/Micro-templating-and-DSL-customizing) to use the properties of bootstrap needs some additional library imports or something? I tried using the same code given there to get a bootstrap feature but it just resulted in a plain css-style. As that section might be old, have there been any changes to that, or do I need to get to import any library or do anything else? Any help will be appreciated.

**Comment by cy6erGn0m** [comment]
Most likely it is bootstrap that have changed somehow these years. Actual attribute names need to be reviewed.

**Comment by sangeetds** [comment]
Hi. Thanks for the comment. Is there any way to make use features of the bootstrap library for now?

**Comment by cy6erGn0m** [comment]
The other possible reason for pure CSS is that the example doesn't include bootstrap CSS at all so you may need to write a style section manually in a head section.

There is no ready library for bootstrap AFAIK. So you need need to write your own extension functions for that purpose. The wiki page you are referring to is what you need as it explains how to write such extensions for any library you need.

**Comment by sangeetds** [comment]
Hello. Thanks for clearing that. I thought maybe the library already contained some readymade styles. Will try to implement my own styles. Thanks a lot.
