### ISSUE TITLE
Outdated Kotlin 1.2.71 badge in README

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.html#162]
It seems the latest version is built with Kotlin 1.4.0, so this badge in the README is quite misleading and might make people think the project has been abandoned which I don't think is the case.

**Comment by IRus** [comment]
Fixed in https://github.com/Kotlin/kotlinx.html/pull/175/files

**Comment by LouisCAD** [comment]
Finally!

Great to see it migrated to Maven Central as well 🙂
