### ISSUE TITLE
Update the README and GitHub Releases for version 0.7.3

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.html#185]
Hello, I noticed that there's a 0.7.3 version of kotlinx.html available on MavenCentral, but the source code and the README haven't been updated for it.

Can you address that please?

Thanks and have a great day!

**Comment by chrisjenx** [comment]
I think it's the same, just published to maven central as jcenter is defunct now.

**Comment by 3flex** [comment]
It's not made as clear as it should be in the README, but Maven Central isn't the repo to use. See here: https://github.com/kotlin/kotlinx.html/wiki/Getting-started#gradle

The repo to use is `https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven`.

That has versions 0.7.2-0.7.5. But agree these should be tagged in GitHub with a changelog so we know what's changed.

**Comment by LouisCAD** [comment]
@e5l ?

**Comment by e5l** [comment]
Hey! The 0.7.3 is the same as the 0.7.2 release but republished to the maven central repository.

**Comment by 3flex** [comment]
Thanks! And what about 0.7.4 (not on Maven Central) and 0.7.5 (which is)?

**Comment by e5l** [comment]
The 0.7.4 version has a publication issue and will be skipped. The 0.7.5 version is listed in releases and published
