### ISSUE TITLE
body.sytle have overflowX and overflowY but not overflow

### ISSUE THREAD

**Issue by ker2x** [Kotlin/kotlinx.html#199]
I don't know if it's on purpose or not, but `document.body!!.style.overflow = "hidden"` doesn't works.

This works : 
```
    document.body!!.style.overflowX = "hidden"
    document.body!!.style.overflowY = "hidden"
```

I expected that setting `style.overflow` set style.overflowX style.overflowY to the same provided value but I got an unresolved reference instead

**Comment by severn-everett** [comment]
`style` refers to an instance of `CSSStyleDeclaration` which is not actually a part of this library, but rather in the [main](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/api/js-v1/org.w3c.dom.css.kt) Kotlin repo, so I'd close this ticket and re-open it over at youtrack.jetbrains.com instead.
