### ISSUE TITLE
Wiki: 'Getting Started' page 404's

### ISSUE THREAD

**Issue by aSemy** [Kotlin/kotlinx.html#207]
I visit https://github.com/Kotlin/kotlinx.html/wiki, and  I see 'Getting Started' in the TOC

<img width="324" alt="image" src="https://user-images.githubusercontent.com/897017/211017966-25e0411d-d883-4081-bad7-9ea276949560.png">

This links to https://github.com/Kotlin/kotlinx.html/Getting-started

However, the URL 404's

<img width="793" alt="image" src="https://user-images.githubusercontent.com/897017/211018056-914e3c41-b9fe-4071-b8c1-49dcd441d7df.png">

**Comment by e5l** [comment]
Hey @aSemy, thanks for the report. The link is already fixed: https://github.com/Kotlin/kotlinx.html/wiki/Getting-started
