### ISSUE TITLE
Add Kotlin/Wasm support

### ISSUE THREAD

**Issue by sdeleuze** [Kotlin/kotlinx.html#210]
I would need Kotlin/Wasm support for this library, I have various related use cases in https://github.com/sdeleuze/kowasm, see https://seb.deleuze.fr/the-huge-potential-of-kotlin-wasm/ for more context.

**Comment by sdeleuze** [comment]
I have created a WASM version in https://github.com/sdeleuze/kowasm/tree/main/kotlinx-html-wasm for now until Kotlin/Wasm support reaches upstream.

It is super close to Kotlin/JS support so common code could maybe be shared using hierarchical project structure.

I had to change `asDynamic()[name] = callback`  to `addEventListener(name.substring(2), callback as (org.w3c.dom.events.Event) -> Unit)`  in `dom-js.kt`, I have made @skuzmich aware there may be something to fix there.

**Comment by e5l** [comment]
Released in `0.11.0`

**Comment by bashor** [comment]
@e5l it looks like it's not published properly to maven central. 404 on https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-html-wasm-js/.

**Comment by e5l** [comment]
Hey @bashor, thanks for the notice. I've found and fixed the publication issue. The files have already been published and will be available shortly!
