### ISSUE TITLE
JS Artifact for 0.8.1 missing

### ISSUE THREAD

**Issue by jschneider** [Kotlin/kotlinx.html#218]
Maybe I am missing something? But I think the 0.8.1 artifact is missing:

404: https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-html-js/0.8.1 

The JVM artifact has been deployed:

https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.8.1

**Comment by jschneider** [comment]
The 0.9.0 version does not have a JVM artifact either.

https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.9.0/

Is this a bug or feature? Has something changed in the way to use kotlinx.html?

**Comment by e5l** [comment]
Thanks, let me check

**Comment by e5l** [comment]
Fixed, 0.9.0 is on central
