### ISSUE TITLE
JVM artifact for 0.9.0 missing from Maven Central

### ISSUE THREAD

**Issue by axelfontaine** [Kotlin/kotlinx.html#225]
Only the base artifact without the `-jvm` suffix is present.

**Comment by aSemy** [comment]
Both JVM and JS are missing a 0.9.0 release

* https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-html-js/
* https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/

**Comment by e5l** [comment]
Fixed, 0.9.0 is on central
