### ISSUE TITLE
FormMethod values "put" and "delete" are invalid

### ISSUE THREAD

**Issue by flqw** [Kotlin/kotlinx.html#25]
As per HTML5 standard, only "get" and "post" are allowed, see https://www.w3.org/TR/html5/forms.html#attr-fs-method

**Comment by cy6erGn0m** [comment]
Yes, initially it was allowed to specify any form method but after that it was forbidden in the final specification version. However it is still open question and there are a lot of discussions around the issue but still no decision. But there is https://www.w3.org/TR/form-http-extensions that defines any methods.

For now we can deprecate non-conformant method values

**Comment by flqw** [comment]
Seems good to me, as long as there is any kind of warning as those values won't work in most browsers.

**Comment by cy6erGn0m** [comment]
ok, I see we need to mark them deprecated to avoid confusion

**Comment by cy6erGn0m** [comment]
Fixed in 0.6.5
