### ISSUE TITLE
Errors in blocks are not catched

### ISSUE THREAD

**Issue by gzoritchak** [Kotlin/kotlinx.html#29]
Only Exceptions are: 

https://github.com/Kotlin/kotlinx.html/blob/master/shared/src/main/kotlin/api.kt#L50

The visit function should catch Trowable.

**Comment by kosiakk** [comment]
The problem seems to be fixed in 4ad3daffbc3176976b4af919e6b9491a366fc2a2

**Comment by cy6erGn0m** [comment]
fixed since 0.6.2
