### ISSUE TITLE
input: add support for minlength

### ISSUE THREAD

**Issue by mfulton26** [Kotlin/kotlinx.html#30]
I see there is a `maxLength` property for HTML5's `maxlength` but I don't see a `minLength` property for HTML5's `minlength`. Can this be added?

**Comment by cy6erGn0m** [comment]
Is it actually supported? Tried in firefox but it seems that it has no any effect?

**Comment by cy6erGn0m** [comment]
what you need are `pattern` and `required` attributes: http://stackoverflow.com/questions/10281962/is-there-a-minlength-validation-attribute-in-html5

**Comment by cy6erGn0m** [comment]
I see, it just applied on focus lost only this is why I used to be confused.

**Comment by cy6erGn0m** [comment]
fix available 0.6.6
