### ISSUE TITLE
Source code for kotlinx-html-jvm is missing in jCenter repo

### ISSUE THREAD

**Issue by kosiakk** [Kotlin/kotlinx.html#32]
The package `kotlinx-html-jvm-0.6.1-sources.jar` exists, but it contains only the jvm-specific sources like `dom.kt` and `utilsImpl.ks`.

I guess, the main part should be in `kotlinx-html-common`, but this package is marked as optional in 2d518626e0b69a2c54edafc6a3bddfe4913a0885 and is actually missing in jCenter.

**Comment by cy6erGn0m** [comment]
It is present now in jcenter for 0.6.2 but still IDEA couldn't locate it unless you click "Download sources" in maven tab.

**Comment by kosiakk** [comment]
Thank you, `kotlinx-html-common-0.6.2-sources.jar` is available now (while `kotlinx-html-jvm-0.6.2-sources.jar` is still mostly empty, 2.5 kb and contains 4 files).

The problem sill persists though: since the `.class` files belong to different library than `.kt` files in `-sources.jar`, Idea does not resolve them automatically.

Now I can manually specify that sources for `kotlinx-html-jvm` library can be found in another jar and then navigation works well. Unfortunately, any re-import of Gradle project overwrites/resets those settings.

I would say, since the binary output of `common` is copied to both `jvm` and `js` jars, the same should happen with the sources.

**Comment by olegcherr** [comment]
Any news? Totally agree with @kosiakk:

> I would say, since the binary output of `common` is copied to both `jvm` and `js` jars, the same should happen with the sources.

**Comment by jonnyzzz** [comment]
I cannot make IJ 2017.3 Public Preview too. Looks like a possibly good workaround is to include the common module sources into the `...-jvm` module sources .jar
Also, I created an issue here
https://youtrack.jetbrains.com/v2/issue/KT-20971

**Comment by LouisCAD** [comment]
This issue is really annoying because it prevents you from seeing the default parameter values such as in the `createHtml()` function. Should be high priority.

To the maintainers: What prevents you from fixing this issue?

**Comment by cy6erGn0m** [comment]
Fixed in 0.6.7
