### ISSUE TITLE
Could not find artifact org.jetbrains.kotlinx:kotlinx-html-common:jar:0.6.1

### ISSUE THREAD

**Issue by mfulton26** [Kotlin/kotlinx.html#33]
The following are available at https://bintray.com/kotlin/kotlinx.html/kotlinx.html/0.6.1 but there is no kotlinx-html-common:

- kotlinx-html-0.6.1.pom
- kotlinx-html-assembly-0.6.1.pom
- kotlinx-html-js-0.6.1.pom
- kotlinx-html-jvm-0.6.1.pom

**Comment by cy6erGn0m** [comment]
Caused by https://github.com/gradle/gradle/issues/867 : gradle simply doesn't respect optional dependencies. So we have to publish kotlinx-html-common as well

**Comment by cy6erGn0m** [comment]
@mfulton26 should be fixed in 0.6.2

**Comment by mfulton26** [comment]
Confirmed. Thank you.
