### ISSUE TITLE
+ for text nodes should do a toString on non-strings

### ISSUE THREAD

**Issue by StokeMasterJack** [Kotlin/kotlinx.html#34]
It would be nice if I could do this:

td { +age }

instead of this:

td { +age.toString() }

**Comment by cy6erGn0m** [comment]
Not sure if it makes sense to do `toString` on `Any` as string representation most like wouldn't be user-friendly. Double/float numbers need to be formatted properly in most cases. Boolean values true/false are not good enough for real users as users would love yes/no, enabled/disabled (generally verb/no-verb) instead. Collections generally need to be represented as UL/LI, table/tbody/tr or something else. Enums are generally shouldn't be displayed via `toString()` and most likely need to be localized before append it. Objects with toString() are useful for debugging but don't think that regular users would love to see it. So I believe the only applicable type is integer number. See Issue #35 for details about +number.
