### ISSUE TITLE
Make the + operator accept non-strings 

### ISSUE THREAD

**Issue by StokeMasterJack** [Kotlin/kotlinx.html#35]
This would shorten the following code:

```
td { +x.toString() }
td { +y.toString() }
td { +z.toString() }
```

to look like this:

```
td { +x }
td { +y }
td { +z }
```

**Comment by cy6erGn0m** [comment]
for sure it is impossible to make unary plus accept numbers is there is already unary plus operator for numbers and it would be too dangerous

the only alternative I see is to add functions `text(String)` and `text(Number)` so it will look like this

```kotlin
td { text(x) }
td { text(y) }
td { text(z) }
```

**Comment by kosiakk** [comment]
What about `fun Tag.text(Any)`, which will deprecate the hack with `+`?
This will solve #5 as well.

**Comment by cy6erGn0m** [comment]
@kosiakk for now I've added `Tag.text(String)`, `Tag.text(Number)`, `Tag.entity(Entities)` and `Unsafe.raw(String)`, `Unsafe.raw(Number)` and `Unsafe.entity(Entities)`. I don't like the idea to handle `Any` as it is generally not good idea to display object's toString representation to end users (see my comment https://github.com/Kotlin/kotlinx.html/issues/34#issuecomment-292125525 )
