### ISSUE TITLE
Composition without passing parent

### ISSUE THREAD

**Issue by StokeMasterJack** [Kotlin/kotlinx.html#39]
I would like to compose methods without passing the parent. Need some kind of add method. Something like below:

```
private fun renderGame(g: Game) = document.create.div {
    style = "margin:1rem;padding:1rem;background:yellow;display:flex"
    add(renderHand(g.ph))
    add(renderHand(g.dh))
}

private fun renderHand(h: Hand) = document.create.div {
    style = "margin:1rem;padding:1rem;background:#DDDDDD"
    div { b { +h.name } }
    div {
        h.cards.map { div { it.name } }
    }
    div { b { +"${h.points} points" } }
}
```

**Comment by kosiakk** [comment]
Instead of that you can declare your component function `renderHand` to be defined in `FlowContent`:
```kotlin
private fun FlowContent.renderHand(h:Hand) { 
   div{ 
      style = ... 
   } 
}
```
so that you could call your function directly, with no need for `add` function:
```kotlin
private fun renderGame(g: Game) = document.create.div {
    style = "..."
    renderHand(g.ph)
    renderHand(g.dh)
}
```

**Comment by cy6erGn0m** [comment]
@StokeMasterJack I believe that Alexander (kosiakk) is completely right and this is the best solution. I don't think it is good idea to provide ability to `add` something without type-checking. At least it shouldn't be so easy to do that.
