### ISSUE TITLE
The onSubmitFunction for a form doesn't work.

### ISSUE THREAD

**Issue by Mr-Binary** [Kotlin/kotlinx.html#47]
```javascript
fun restoreListValues(e: Event) {
    println("I'm here")
}

fun doForm(trTag: TR) {
    trTag.td {
        form {
            name = "fmform"
            encType = FormEncType.textPlain
            action = "/server/"
            method = FormMethod.post
            onSubmitFunction = {
                event - > restoreListValues(event)
            }
        }
    }
}
```

After executing, nothing happens to that form, I could use `onSubmit`, and the final form will have the `onsubmit` value, but the problem is that it expects a string, which means I could only refer to the final compiled javascript code which has no way to access the kotlinJS context.

What I want is simple, just use a kotlinJS method to handle the `onsubmit` event of a form.
How to achieve that?

**Comment by cy6erGn0m** [comment]
Doens't explicit return value `true` fix the issue? `onSubmitFunction = { event - > restoreListValues(event); true }`

**Comment by Mr-Binary** [comment]
@cy6erGn0m 
Thanks for the reply
But no...

This is the result:
```html
<form name="fmform" enctype="text/plain" action="" method="post">
```

**Comment by cy6erGn0m** [comment]
Are you trying to generate javascript handler on server side?

**Comment by Mr-Binary** [comment]
Nope, this is the code for the client side, I use kotlinJS

**Comment by cy6erGn0m** [comment]
Are you sure it doesn't print "I'am here"? js dom builder simply do event  handler registration so you can't see it in html. I've just tried to add the following integration test and it works well

```
fun assignEvent() {
        val wrapper = wrapper()
        var invoked = false

        wrapper.append {
            form {
                id = "my-form"
                onSubmitFunction = { event ->
                    invoked = true
                }
            }
        }

        val event = document.createEvent("Event")
        event.initEvent("submit", true, true)

        (wrapper.getElementsByTagName("form").asList().first { it.id == "my-form" } as HTMLFormElement).dispatchEvent(event)

        assertTrue { invoked }
    }
```

**Comment by Mr-Binary** [comment]
It works. Thanks :)
