### ISSUE TITLE
Provide alternate way to set tag content 

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx.html#5]
It should be way to set/append tag content rather than `+` operator

**Comment by kosiakk** [comment]
I'd say `text("message")` it the most reasonable and straight-forward way. It corresponds to DOM API text elements and does exactly what it says - prints text (performing all the escapes on the way).

I'd also reduce `unsafe` from closure with a single method to a simple function, something like `unsafePrintRawHtmlContent("<h1>Expect XSS Here</h1>")`. The method name must be long and scary. Was there other motivation for `Unsafe` class? Filtering, if required, can be done in `TagConsumer`.

I can't imagine situation when `+` in `Unsafe` should be similar to `text`. I think it is wrong and dangerous to reuse the same name here.

**Comment by kosiakk** [comment]
I think, such fake use if `unaryPlus` is exactly why @abreslav does not allow operators like `>>=` in Kotlin.
