### ISSUE TITLE
Couldn't get updated value from text input

### ISSUE THREAD

**Issue by Albert-Gao** [Kotlin/kotlinx.html#50]
Environment: `Kotlin JS 1.1.4-3` with `kotlinx.html 0.6.4`

### What I did:
1. Add a text input and add a button
2. Click the button to retrieve the latest value from the input
3. Can't get the updated value, always the original `test text`

I use the following javascript, it works as expected, `document.getElementByID('TestInput').value`

The code is as follows:
A bug or am I doing something wrong?

```kotlin
import kotlinx.html.*
import kotlinx.html.dom.create
import kotlinx.html.js.*
import org.w3c.dom.Element
import org.w3c.dom.events.Event
import kotlin.browser.*

fun onClick(e:Event){
    val element = document.getElementById("TestInput")
    window.alert(element?.getAttribute("value").toString())
}

fun main(args: Array<String>) {
    val root: Element = document.getElementById("root")!!

    val myDiv = document.create.div {
        input(InputType.text) {
            id="TestInput"
            value="test text"
        }
        button {
            +"Get input.value"
            onClickFunction=::onClick
        }
    }

    root.appendChild(myDiv)
}
```

**Comment by cy6erGn0m** [comment]
?

```
val element = document.getElementById("TestInput") as HTMLInputElement
window.alert(element?.value)
```

**Comment by DavidWhit** [comment]
You're setting the actual value and then getting that value so it would be the same. I assume then you're changing it and the using js and see the value is what you'd expect. If you want a default you should set defaultValue. I'd also suggest an onChangeFunction vs onClickFunction.
