### ISSUE TITLE
Attribute Extensions don't work.

### ISSUE THREAD

**Issue by chrisjenx** [Kotlin/kotlinx.html#52]
I was trying to add additional attribute properties to make some of them easier, but setting attributes as extension properties never prints out to the final html.

For example, adding a `data-toggle` attribute to a button:

```
var BUTTON.dataToggle: String?
    get() = attributes["data-toggle"]
    set(value) {
        attributes["data-toggle"]
    }
```

Calling this, doesn't work:
```
button {
    classes = setOf("navbar-toggler", "d-lg-none")
    type = ButtonType.button
    dataToggle = "dropdown"
}
```

But this does:

```
button {
    classes = setOf("navbar-toggler", "d-lg-none")
    type = ButtonType.button
    attributes["data-toggle"] = "dropdown"}
```

Is there something weird going on that I can't see?

**Comment by cy6erGn0m** [comment]
What do you mean by "never prints out to the final html" ? how does it look like? the extension property you provided should work. Is is server-side or client side?

**Comment by chrisjenx** [comment]
@cy6erGn0m this was using html module in ktor, It just never prints out the html for that page I'm loading.

**Comment by cy6erGn0m** [comment]
@chrisjenx ah, please notice that attribute assignment is missing in property setter 

```kotlin
var BUTTON.dataToggle: String?
    get() = attributes["data-toggle"]
    set(value) {
        attributes["data-toggle"]   /// here attribute is not assigned
        // should be 
        // attributes["data-toggle"] = value
    }
```

this is why it doens't work
