### ISSUE TITLE
HTTP PATCH method?

### ISSUE THREAD

**Issue by Miha-x64** [Kotlin/kotlinx.html#57]
Hello.
If `FormMethod` enumerates only [standard form.action methods](https://www.w3schools.com/tags/att_form_method.asp), why there are `PUT` and `DELETE`? If not, where's `PATCH`?

Methods, other than `GET` and `POST`, seem to be prohibited:
https://stackoverflow.com/a/8054241/3050249
https://softwareengineering.stackexchange.com/a/211790

**Comment by cy6erGn0m** [comment]
Duplicate of issue #25
