### ISSUE TITLE
Examples and Standard Project Structure?

### ISSUE THREAD

**Issue by TheMonitorLizard** [Kotlin/kotlinx.html#60]
Possibly a wiki page with examples and regarding a standard project structure or layout, maybe also an example module in the repository.

Currently looking to attempt creating an entire website with kotlin2js and this library, very excited, but I am unsure how exactly to structure my project directories and the like.

**Comment by cy6erGn0m** [comment]
kotlinx.html is a library not a framework so there is no standard project structure. Please see https://github.com/Kotlin/kotlin-fullstack-sample for full project example
