### ISSUE TITLE
upload to maven central

### ISSUE THREAD

**Issue by hennr** [Kotlin/kotlinx.html#81]
To avoid adding another repo to my projects I would love to see kotlinx-html-jvm to be available on mvn central instead of bintray only.

**Comment by caleb-allen** [comment]
Looks like it's available on jcenter:

```groovy
repositories {
    jcenter()
}

dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-html-jvm:$kotlinx_version"
}
```

**Comment by BraisGabin** [comment]
Please, upload to Maven Central. We are using this library in our own library that it's uploaded to Maven Central. But, because of this library, our users need to add `jCenter` too.

**Comment by fr1zle** [comment]
It would be great if this library was available in maven central.
If i remember correctly there used to be some security issues with using jcenter and we would prefer to be able to stick to maven central.

**Comment by keyboardr** [comment]
Now that JCenter is being sunset, this should be a much higher priority.

Context: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by Kobe** [comment]
update: I've asked one of the Jetbrain'ers and they are on it, see https://twitter.com/Kobe/status/1362302455728504832

**Comment by hfhbd** [comment]
Alternative use Jetbrains Space:
```kotlin
repositories {
    maven(url = "https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-html-js:0.7.3")
}
```

**Comment by christian-draeger** [comment]
to quote @e5l here: 
> We're working on republishing old artifacts to central. There are several central requirements broken and it takes time to make all stuff right. We made the Space publication because it was the fastest way to provide artifacts, while we working on porting everything to central. Sorry for the delay and confusion.

https://github.com/Kotlin/kotlinx.html/issues/173#issuecomment-823011760

**Comment by e5l** [comment]
0.7.3 is available in mavenCentral
