### ISSUE TITLE
unable to insert raw content into script tag

### ISSUE THREAD

**Issue by abendt** [Kotlin/kotlinx.html#83]
the documentation (https://github.com/kotlin/kotlinx.html/wiki/Style-and-script-tags) says that it should be possible to insert raw content into a script tag.

This does not seem to work if I'm using the _createHTMLDocument_  builder as then the inserted "raw" content needs to be valid XML. The example below causes a SAXParseException.

```
val html = createHTMLDocument().body {
            script(type = ScriptType.textJScript) {
                unsafe {
                    raw("""
                        function my() {return 1;}
                        """)
                }
            }
        }.serialize(true)
```

Is this intended? 

I also setup a sample project to demonstrate the issue:  https://github.com/abendt/kotlin-html-jscript/blob/master/src/test/kotlin/HtmlScriptTest.kt

**Comment by cy6erGn0m** [comment]
Have you tried to wrap your script with `// <!-- ` and `// -->`. It's quite old trick that could help to workaround the issue

**Comment by cy6erGn0m** [comment]
Unfortunatetly there are limitations for unsafe raw content in DOM mode. This particular case need to be fixed somehow.

**Comment by abendt** [comment]
we tried to wrap the script with comments with no success (see https://github.com/abendt/kotlin-html-jscript/blob/master/src/test/kotlin/HtmlScriptTest.kt)

Our current workaround is to use the Streaming/String based builders.
