### ISSUE TITLE
prepend next to append

### ISSUE THREAD

**Issue by robstoll** [Kotlin/kotlinx.html#86]
would be nice if there is also a `prepend` function next to `append`.

**Comment by cy6erGn0m** [comment]
Are you talking about this https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/prepend ?

**Comment by robstoll** [comment]
Not exactly but kind of. I currently do this:
```
val div = document.create.div { ... }
element.insertBefore(div, element.firstChild)
```
Would be nice if kotlinx.html has a `prepend` function so that I can write: 
```
element.prepend {
  div { ... } 
}
```
