### ISSUE TITLE
iframe missing

### ISSUE THREAD

**Issue by Miclebrick** [Kotlin/kotlinx.html#93]
there does not seem to be an iframe tag - at least, not one IDEA can find...

**Comment by spand** [comment]
Version? There are many variations available like:
```
@HtmlTagMarker
fun FlowOrInteractiveOrPhrasingContent.iframe(sandbox : IframeSandbox? = null, classes : String? = null, block : IFRAME.() -> Unit = {}) : Unit = IFRAME(attributesMapOf("sandbox", sandbox?.enumEncode(),"class", classes), consumer).visit(block)
```

**Comment by Miclebrick** [comment]
`
buildscript {
    ext.kotlin_version = '1.2.50'
    ext.ktor_version = '0.9.3'
}

[...]    

repositories {
    mavenCentral()
    jcenter()
    maven { url "https://dl.bintray.com/kotlin/ktor" }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    compile "io.ktor:ktor-server-netty:$ktor_version"
    compile "io.ktor:ktor-auth:$ktor_version"
    compile "org.jetbrains.kotlinx:kotlinx-html-jvm:0.6.11"
    compile "io.ktor:ktor-html-builder:$ktor_version"
    compile "ch.qos.logback:logback-classic:1.2.1"
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
`

that's what i have in my build script

**Comment by cy6erGn0m** [comment]
There are `IFRAME` type and `iframe` functions. Most likely you are trying to place iframe in a wrong tag.
